In [1]:
import numpy as np

# Comparar kernels

In [13]:
k1orig = np.loadtxt('../Original/drug_response_data/Cell_line_kernels/Kc_methylation_210.txt')
k1modi = np.loadtxt('../Scenario 2/data_base/Scenario-02/Iteration-02/Scenario_02_zero_70/Cell_line_kernels/Kc_methylation_210.txt')

print(k1orig.mean(), k1modi.mean())
k1orig - k1modi

0.5964670209042375 0.1808850466783387


array([[0.        , 0.81205977, 0.8842749 , ..., 0.70940347, 0.74512409,
        0.70449113],
       [0.81205977, 0.        , 0.        , ..., 0.67430077, 0.67513474,
        0.65916813],
       [0.8842749 , 0.        , 0.        , ..., 0.69905017, 0.        ,
        0.68810842],
       ...,
       [0.70940347, 0.67430077, 0.69905017, ..., 0.        , 0.7222642 ,
        0.80402812],
       [0.74512409, 0.67513474, 0.        , ..., 0.7222642 , 0.        ,
        0.        ],
       [0.70449113, 0.65916813, 0.68810842, ..., 0.80402812, 0.        ,
        0.        ]])

# Comparar resultados

## Pesos

In [30]:
# path_f1_original = '../Original/drug_response_data/RMSE.txt'

pesos_orig = np.loadtxt('../Original/drug_response_data/pairwise_kernel_weights.txt').mean(axis=0)
pesos_modi = np.loadtxt('../Scenario 2/data_base/Scenario-02/Iteration-02/Scenario_02_zero_70/pairwise_kernel_weights.txt').mean(axis=0)

kernel_names = open('../Original/drug_response_data/pairwise_kernel_names.txt','r').read().split('\t')
kernel_names[0:3]
# pesos_modi - pesos_orig

['Kd_PubChem.txt_KRONECKER_Kc_cn_146.txt',
 'Kd_PubChem.txt_KRONECKER_Kc_cn_270.txt',
 'Kd_PubChem.txt_KRONECKER_Kc_cn_417.txt']

In [31]:
pos = []
for i, x in enumerate(kernel_names):
    if 'Kc_methylation_210' in x:
        pos.append(i)
pos

[7, 19, 31, 43, 55, 67, 79, 91, 103, 115]

In [37]:
kernel_names[19]

'Kd_circular.txt_KRONECKER_Kc_methylation_210.txt'

In [33]:
pesos_modi.shape

(120,)

In [50]:

print(pesos_orig[pos].mean())
print(pesos_modi[pos].mean())

(pesos_orig[pos].mean() - pesos_modi[pos].mean()) / pesos_orig[pos].mean()

# (np.abs(pesos_orig[pos]) - np.abs(pesos_modi[pos])).mean()

3.266941675905568e-08
3.2406032549887104e-10


0.9900806210319306

In [48]:
print(pesos_modi[pos])
print(pesos_orig[pos])

(np.abs(pesos_orig) - np.abs(pesos_modi)).mean()

[-1.50046226e-09  9.16677550e-12 -4.57715547e-10 -1.82525684e-11
  3.63432682e-10  1.89143712e-09  1.84136452e-09 -1.45296007e-09
  6.89089977e-10  1.87550263e-09]
[2.38535619e-10 2.53146954e-09 3.34624212e-08 3.38218386e-09
 5.32663617e-08 6.42223965e-08 9.97801797e-08 2.03376212e-09
 5.49175498e-08 1.28593075e-08]


-7.686821168944986e-10

In [41]:
(np.abs(pesos_modi) - pesos_orig)

array([-1.75017952e-09, -1.32265901e-09, -1.18319583e-09, -1.82026928e-09,
       -1.87777160e-09, -2.01093889e-09, -1.55882308e-09, -1.73899788e-09,
       -1.60272282e-09, -1.41422820e-09, -1.61695314e-09, -1.29682228e-09,
       -8.60815707e-09, -3.76979084e-09, -2.16618809e-09, -4.11971539e-09,
       -3.76995289e-09, -3.51395774e-09, -5.14075333e-09, -2.52230277e-09,
       -2.91601705e-09, -1.80569690e-09, -5.02434580e-09, -3.44212950e-09,
       -5.45256848e-09, -1.57138159e-08, -4.64052197e-06, -2.91591216e-08,
       -5.16220600e-08, -1.51248527e-07, -1.47046750e-08, -3.39201367e-08,
        8.30455243e-06, -1.83467858e-06, -6.59915201e-09, -1.09499825e-08,
       -3.60491426e-09, -3.62484857e-09, -3.20075641e-09, -3.56615165e-09,
       -4.35825318e-09, -4.17731397e-09, -5.11887237e-09, -3.40043642e-09,
       -4.03950771e-09, -2.89332709e-09, -3.88712039e-09, -3.62397001e-09,
       -6.84926301e-09, -1.72470372e-08,  6.82539685e-06, -3.95793055e-08,
       -8.27360405e-08,  

In [10]:
# path_f1_modificado = '../Scenario 2/data_base/Scenario-02/Iteration-02/Scenario_02_zero_70/RMSE.txt'
path_f1_modificado = '../Scenario 2/data_base/Scenario-02/Iteration-02/Scenario_02_zero_70/pairwise_kernel_weights.txt'
xx2 = np.loadtxt(path_f1_original)
xx2

array([[ 6.72237503e-09,  4.68430428e-09,  5.41965999e-09, ...,
         3.66239502e-08,  3.51156730e-08,  3.31287403e-08],
       [ 1.37466878e-09,  5.29954147e-10,  2.04587614e-09, ...,
         9.60503016e-09,  9.34872144e-09,  8.51554963e-09],
       [ 2.18111853e-08,  1.70354675e-08,  1.54885364e-08, ...,
         4.48889944e-08,  5.54863338e-08,  5.04506944e-08],
       ...,
       [-3.37559371e-09, -3.67727312e-09, -1.31989334e-09, ...,
         1.94142498e-10, -2.41522572e-09, -2.36497331e-09],
       [-9.95695935e-10, -1.16368305e-09, -4.83394062e-10, ...,
        -5.21872666e-10, -1.02223701e-09, -9.99229596e-10],
       [-5.09662942e-09, -4.94657647e-09, -5.47469525e-10, ...,
         6.84741057e-09,  6.31544357e-10,  1.13460374e-09]])

In [11]:
xx1-xx2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])